name : DevFlow CI

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: devflow_db
          MYSQL_ROOT_PASSWORD: 211006
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: Run tests
        run: ./mvnw test
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/devflow_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 211006

